# Generated by Django 2.2.7 on 2020-02-06 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_menupage'),
    ]

    operations = [
        migrations.AddField(
            model_name='menupage',
            name='restaurant_menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_menu', to='user.RestaurantTruck'),
        ),
    ]
