# Generated by Django 2.2.7 on 2020-02-14 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_menupage_restaurant_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='restauranttruck',
            name='lat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='restauranttruck',
            name='long',
            field=models.FloatField(default=0),
        ),
    ]
